### ISSUE TITLE
Greseli minore de ortografie

### ISSUE THREAD

**Issue by Andrei-III** [sorinfederiga/cuba-translation-ro#1]
Salut.

Am instalat addon-ul si am gasit cateva greseli minore de ortografie.

Prima ar fi "Crează" in loc "Creează" cum ar fi corect.
Am gasit asta in 26 de mesaje prin global, gui si web.

A doua ar fi "Proprietâți" in loc de "Proprietăți".
Am gasit asta doar intr-un mesaj: **filter.addCondition.propertyConditions**

![image](https://user-images.githubusercontent.com/13452678/64032300-d4d50d80-cb52-11e9-9699-b3ff841729be.png)

Merci de traducere, mi-a scutit o gramada de timp. Spor !

**Comment by sorinfederiga** [comment]
Salut,

Multumesc pentru observatii. Le-am corectat.
